---
  :caps:
    :platformName: 'iOS'
    :platformVersion: '12.4'
    :deviceName: 'iPhone 7'
    :automationName: 'XCUITest'
    :fullReset: true
    :app: '/Users/asusters/Desktop/protect/test-protect-cucumber/apps/UniFi Protect.ipa'
